// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = ".app__header {\n    padding: 1rem;\n    display: flex;\n    justify-content: space-between;\n    position: fixed;\n    width: 100vw;\n    top: 0;\n    z-index: 1;\n    transition: background 0.25s;\n}\n\n.app__header_scrolled {\n    background-color: black;\n}\n\n.app__header_mobile {\n    display: none;\n}\n\n.app__header_scrolled {\n    background-color: black;\n}\n\n.app__header_title {\n    font-size: 1.25rem;\n    text-transform: uppercase;\n    font-weight: 600;\n}\n\n.app__header_search {\n    min-width: 50%;\n    display: flex;\n    align-items: center;\n    border: 1px solid var(--white);\n    padding: 0 0.25rem;\n    border-radius: 3px;\n    transition: background-color 0.25s;\n}\n\n.app__header_search:hover {\n    background-color: rgba(255, 255, 255, 0.1);\n}\n\n.app__header_search_input {\n    min-width: 86%;\n    border: none;\n    font-size: 0.65rem;\n    padding: 0.25rem;\n    background: none;\n    color: white;\n}\n\n.app__header_search_input:focus {\n    outline: none;\n}\n\n.app__header_search_bar_icon {\n    margin-right: 0.25rem;\n}\n\n.app__header_search_bar_icon,\n.app__header_search_icon {\n    width: 18px;\n    height: 18px;\n}\n\n.app__header_button {\n    background-color: var(--red);\n    color: white;\n}\n\n.app__header_button:hover {\n    background-color: var(--darker-red);\n}\n\n.app__header_collection_button {\n    background-color: var(--white);\n    color: black;\n}\n\n.app__header_collection_button:hover {\n    background-color: rgba(255, 255, 255, 0.75);\n}\n\n.app__header_search_button {\n    background-color: var(--red);\n    color: white;\n}\n\n.app__header_search_button:hover {\n    background-color: var(--darker-red);\n}\n\n.app__header_icon {\n    margin-right: 0.25rem;\n}\n\n/* This will handle ipad and smaller devices */\n@media screen and (max-width: 768px) {\n    .app__header_desktop {\n        display: none;\n    }\n\n    .app__header_mobile {\n        display: block;\n    }\n\n    .app__header_mobile_title {\n        display: flex;\n        justify-content: space-between;\n        margin-bottom: 1rem;\n    }\n\n    .app__header_mobile_search .app__header_search_input {\n        font-size: 0.8rem;\n    }\n\n    .app__header_text {\n        display: none;\n    }\n\n    .app__header_icon {\n        margin-right: 0;\n    }\n}\n";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}