// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = ":root {\n    --black: #0e0e0e;\n    --white: #ffffff;\n    --light-grey: #444343;\n    --grey: #302f2f;\n    --red: #e50a13;\n    --darker-red: #a8060b;\n    --jayz-blue: #211abf;\n}\n\n* {\n    box-sizing: border-box;\n}\n\nhtml,\nbody {\n    margin: 0;\n    padding: 0;\n    box-sizing: border-box;\n    font-size: 24px;\n    font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif;\n    font-weight: normal;\n    -webkit-font-smoothing: antialiased;\n    background-color: var(--black);\n    color: var(--white);\n}\n\n.app {\n    box-sizing: border-box;\n}\n\n.app__button {\n    padding: 0.25rem 0.5rem;\n    transition: background-color 0.25s;\n    border: 0;\n    font-weight: bold;\n    cursor: pointer;\n    display: inline-flex;\n    align-items: center;\n    text-transform: uppercase;\n    font-size: 0.65rem;\n    border-radius: 3px;\n}\n\n.app__no_style_button {\n    background: none;\n    border: none;\n    cursor: pointer;\n}\n\n.app__no_style_button:focus {\n    outline: none;\n}\n\n@keyframes spin {\n    from {\n        transform: rotate(0deg);\n    }\n    to {\n        transform: rotate(360deg);\n    }\n}\n\n.app__loading_screen {\n    display: none;\n    position: fixed;\n    top: 0;\n    width: 100%;\n    height: 100%;\n    left: 0;\n    background: rgba(0, 0, 0, 0.85);\n    z-index: 2;\n}\n\n.app__loading_text {\n    margin-right: 0.25rem;\n}\n\n.app__loading_star {\n    position: relative;\n    top: 2px;\n    width: 24px;\n    height: 24px;\n    animation-name: spin;\n    animation-duration: 2000ms;\n    animation-iteration-count: infinite;\n    animation-timing-function: linear;\n}\n\n.app__loading_screen_show {\n    display: flex;\n    justify-content: center;\n    align-items: center;\n}\n\n.app__footer {\n    display: flex;\n    justify-content: space-around;\n    padding: 2rem 1rem;\n    font-size: 0.5rem;\n}\n\n.app__footer_color {\n    background-color: var(--jayz-blue);\n}\n\n@media screen and (max-width: 768px) {\n    .app__footer {\n        display: block;\n    }\n\n    .app__footer > div {\n        margin-bottom: 0.5rem;\n    }\n}\n";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';
  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}